server:
  port: 8082

spring:
  application:
    name: library-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Library_DB
    username: postgres
    password: 112358
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    enabled: true