server:
  port: 8082

spring:
  application:
    name: library-service
  datasource:
    url: jdbc:postgresql://db-library:5432/library_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    enabled: true