server:
  port: 8084

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/User_DB
    username: postgres
    password: 112358
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    enabled: true

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000