server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: book-service-route
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**
          filters:
            - StripPrefix=3

        - id: library-service-route
          uri: lb://library-service
          predicates:
            - Path=/api/v1/library/**
          filters:
            - StripPrefix=3

eureka:
  client:
    healthcheck:
      enabled: true
logging:
  level:
    org.springframework: debug