server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: book-service-route
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**
          filters:
            - StripPrefix=3

        - id: library-service-route
          uri: lb://library-service
          predicates:
            - Path=/api/v1/library/**
          filters:
            - StripPrefix=3

        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

eureka:
  client:
    healthcheck:
      enabled: true
logging:
  level:
    org.springframework: debug

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    prefix: "Bearer"
