server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Book_DB
    username: postgres
    password: 112358
  jpa:
    hibernate:
      ddl-auto: update   # ?????????????? ?????????? ????? ??
    show-sql: true       # ??????????? SQL ????????